# Generated by Django 4.2.7 on 2025-12-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
