# Generated by Django 4.2.7 on 2025-12-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instructor_profile_picture'),
        ('problems', '0002_problem_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProblemRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_ratings', to='accounts.instructor')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemBankRatingScaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('problem_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_scale_options', to='problems.problembank')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProblemBankRatingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('criterion_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('problem_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_criteria', to='problems.problembank')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProblemRatingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_id', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='problems.instructorproblemrating')),
            ],
        ),
        migrations.AddConstraint(
            model_name='problembankratingscaleoption',
            constraint=models.UniqueConstraint(fields=('problem_bank', 'value'), name='unique_bank_scale_value'),
        ),
        migrations.AddConstraint(
            model_name='problembankratingcriterion',
            constraint=models.UniqueConstraint(fields=('problem_bank', 'criterion_id'), name='unique_bank_criterion_id'),
        ),
        migrations.AddConstraint(
            model_name='instructorproblemratingentry',
            constraint=models.UniqueConstraint(fields=('rating', 'criterion_id'), name='unique_rating_entry_criterion'),
        ),
        migrations.AddConstraint(
            model_name='instructorproblemrating',
            constraint=models.UniqueConstraint(fields=('problem', 'instructor'), name='unique_instructor_problem_rating'),
        ),
    ]
