# Generated by Django 4.2.7 on 2025-12-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_instructorproblemrating_problembankratingscaleoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorproblemratingentry',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='problembankratingscaleoption',
            name='value',
            field=models.FloatField(),
        ),
    ]
