# Generated by Django 4.2.7 on 2025-12-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_instructorproblemratingentry_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problembankratingcriterion',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
