# Generated by Django 4.2.7 on 2025-12-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instructor_profile_picture'),
        ('problems', '0005_problembankratingcriterion_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics', to='accounts.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='RubricScaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('label', models.CharField(max_length=255)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_options', to='problems.rubric')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('criterion_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.IntegerField(default=1)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='problems.rubric')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='problembank',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_banks', to='problems.rubric'),
        ),
        migrations.AddConstraint(
            model_name='rubricscaleoption',
            constraint=models.UniqueConstraint(fields=('rubric', 'value'), name='unique_rubric_scale_value'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'criterion_id'), name='unique_rubric_criterion_id'),
        ),
    ]
