# Generated by Django 4.2.7 on 2025-12-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_rubric_rubricscaleoption_rubriccriterion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problembankratingscaleoption',
            name='problem_bank',
        ),
        migrations.DeleteModel(
            name='ProblemBankRatingCriterion',
        ),
        migrations.DeleteModel(
            name='ProblemBankRatingScaleOption',
        ),
    ]
