# Generated by Django 4.2.7 on 2025-12-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instructor_profile_picture'),
        ('problems', '0007_remove_problembankratingscaleoption_problem_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='is_global',
        ),
        migrations.AlterField(
            model_name='rubric',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='accounts.instructor'),
        ),
    ]
