# Generated by Django 4.2.7 on 2025-12-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_remove_rubric_is_global_alter_rubric_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instructorproblemratingentry',
            name='unique_rating_entry_criterion',
        ),
        migrations.RemoveField(
            model_name='instructorproblemratingentry',
            name='criterion_id',
        ),
        migrations.RemoveField(
            model_name='instructorproblemratingentry',
            name='value',
        ),
        migrations.AddField(
            model_name='instructorproblemratingentry',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='instructorproblemratingentry',
            name='scale_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.rubricscaleoption'),
        ),
        migrations.AddConstraint(
            model_name='instructorproblemratingentry',
            constraint=models.UniqueConstraint(fields=('rating', 'criterion'), name='unique_rating_entry_criterion'),
        ),
    ]
