# Generated by Django 4.2.7 on 2025-12-04 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_remove_instructorproblemratingentry_unique_rating_entry_criterion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorproblemratingentry',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.rubriccriterion'),
        ),
        migrations.AlterField(
            model_name='instructorproblemratingentry',
            name='scale_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.rubricscaleoption'),
        ),
    ]
