# Generated by Django 4.2.7 on 2026-02-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_instructorproblemratingentry_criterion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubriccriterion',
            name='weight',
        ),
    ]
