from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    InstructorViewSet,
    CSRFTokenView,
    LoginView,
    LogoutView,
    ProblemBankProblemListCreate,
    ProblemBankViewSet,
    ProblemViewSet,
    PublicAttemptComplete,
    PublicAttemptDetail,
    PublicAttemptSlotAnswer,
    PublicAttemptSlotInteraction,
    PublicQuizDetail,
    PublicQuizStart,
    QuizAllowedInstructorDelete,
    QuizAllowedInstructorList,
    QuizRubricView,
    GradingRubricView,
    QuizSlotGradeView,
    QuizSlotListCreate,
    QuizSlotViewSet,
    QuizAttemptDetail,
    QuizAttemptInteractions,
    QuizAttemptList,
    ResponseConfigView,
    SlotProblemDeleteView,
    SlotProblemListCreate,
    SlotProblemDeleteView,
    SlotProblemListCreate,
    QuizViewSet,
    DashboardStatsView,

    QuizSlotProblemStudentsView,
    ManualResponseView,
    ResponseImportTemplateView,
    ResponseImportView,
    ProblemBankRubricView,
    InstructorProblemRatingView,
    ProblemBankAnalysisView,
    ProblemBankRatingImportView,
    RubricViewSet,
    RubricViewSet,

    GlobalInstructorAnalysisView,
    GlobalStudentAnalysisView,
    GlobalCorrelationAnalysisView,
    GlobalAgreementAnalysisView,
    QuizGradeExportView,
    QuizAnalyticsView,
    QuizOverviewAnalyticsView,
    QuizInteractionAnalyticsView,
    QuizSlotAnalyticsView,
    QuizInterRaterAgreementView,
    GlobalInteractionAnalyticsView,
    QuizProjectScoreListCreateView,
    GlobalProjectAnalysisView,
)

router = DefaultRouter()
router.register('instructors', InstructorViewSet, basename='instructor')
router.register('problem-banks', ProblemBankViewSet, basename='problem-bank')
router.register('problems', ProblemViewSet, basename='problem')
router.register('quizzes', QuizViewSet, basename='quiz')
router.register('slots', QuizSlotViewSet, basename='slot')
router.register('rubrics', RubricViewSet, basename='rubric')

urlpatterns = [
    path('auth/csrf/', CSRFTokenView.as_view(), name='api-csrf'),
    path('auth/login/', LoginView.as_view(), name='api-login'),
    path('auth/logout/', LogoutView.as_view(), name='api-logout'),
    path('', include(router.urls)),
    path('problem-banks/<int:bank_id>/problems/', ProblemBankProblemListCreate.as_view(), name='bank-problems'),
    path('problem-banks/<int:bank_id>/rubric/', ProblemBankRubricView.as_view(), name='bank-rubric'),
    path('problem-banks/<int:bank_id>/analysis/', ProblemBankAnalysisView.as_view(), name='bank-analysis'),

    path('problem-banks/analysis/global/instructor/', GlobalInstructorAnalysisView.as_view(), name='global-analysis-instructor'),
    path('problem-banks/analysis/global/student/', GlobalStudentAnalysisView.as_view(), name='global-analysis-student'),
    path('problem-banks/analysis/global/correlation/', GlobalCorrelationAnalysisView.as_view(), name='global-analysis-correlation'),
    path('problem-banks/analysis/global/agreement/', GlobalAgreementAnalysisView.as_view(), name='global-analysis-agreement'),
    path('problem-banks/analysis/global/interactions/', GlobalInteractionAnalyticsView.as_view(), name='global-interactions'),
    path('problem-banks/analysis/global/project-scores/', GlobalProjectAnalysisView.as_view(), name='global-project-scores'),
    path('problem-banks/<int:bank_id>/import-ratings/', ProblemBankRatingImportView.as_view(), name='bank-import-ratings'),
    path('problems/<int:problem_id>/rate/', InstructorProblemRatingView.as_view(), name='problem-rate'),
    path('quizzes/<int:quiz_id>/slots/', QuizSlotListCreate.as_view(), name='quiz-slots'),
    path('quizzes/<int:quiz_id>/allowed-instructors/', QuizAllowedInstructorList.as_view(), name='quiz-allowed-list'),
    path(
        'quizzes/<int:quiz_id>/allowed-instructors/<int:instructor_id>/',
        QuizAllowedInstructorDelete.as_view(),
        name='quiz-allowed-delete',
    ),
    path('quizzes/<int:quiz_id>/rubric/', QuizRubricView.as_view(), name='quiz-rubric'),
    path('quizzes/<int:quiz_id>/grading-rubric/', GradingRubricView.as_view(), name='quiz-grading-rubric'),

    path('quizzes/<int:quiz_id>/analytics/', QuizAnalyticsView.as_view(), name='quiz-analytics'),
    path('quizzes/<int:quiz_id>/analytics/overview/', QuizOverviewAnalyticsView.as_view(), name='quiz-analytics-overview'),
    path('quizzes/<int:quiz_id>/analytics/interactions/', QuizInteractionAnalyticsView.as_view(), name='quiz-analytics-interactions'),
    path('quizzes/<int:quiz_id>/analytics/agreement/', QuizInterRaterAgreementView.as_view(), name='quiz-analytics-agreement'),
    path('quizzes/<int:quiz_id>/analytics/slots/<int:slot_id>/', QuizSlotAnalyticsView.as_view(), name='quiz-analytics-slot'),
    path(
        'quizzes/<int:quiz_id>/analytics/slots/<int:slot_id>/problems/<int:problem_id>/students/',
        QuizSlotProblemStudentsView.as_view(),
        name='quiz-slot-problem-students',
    ),
    path('quizzes/<int:quiz_id>/manual-response/', ManualResponseView.as_view(), name='quiz-manual-response'),
    path('quizzes/<int:quiz_id>/import-template/', ResponseImportTemplateView.as_view(), name='quiz-import-template'),
    path('quizzes/<int:quiz_id>/import-responses/', ResponseImportView.as_view(), name='quiz-import-responses'),
    path('quizzes/<int:quiz_id>/attempts/', QuizAttemptList.as_view(), name='quiz-attempts'),
    path(
        'quizzes/<int:quiz_id>/attempts/<int:attempt_id>/',
        QuizAttemptDetail.as_view(),
        name='quiz-attempt-detail',
    ),
    path(
        'quizzes/<int:quiz_id>/attempts/<int:attempt_id>/interactions/',
        QuizAttemptInteractions.as_view(),
        name='quiz-attempt-interactions',
    ),
    path(
        'quizzes/<int:quiz_id>/attempts/<int:attempt_id>/slots/<int:slot_id>/grade/',
        QuizSlotGradeView.as_view(),
        name='quiz-slot-grade',
    ),
    path(
        'quizzes/<int:quiz_id>/grades/export/',
        QuizGradeExportView.as_view(),
        name='quiz-grade-export',
    ),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard-stats'),
    path('slots/<int:slot_id>/slot-problems/', SlotProblemListCreate.as_view(), name='slot-problem-list'),
    path('slot-problems/<int:pk>/', SlotProblemDeleteView.as_view(), name='slot-problem-delete'),
    path('public/quizzes/<slug:public_id>/', PublicQuizDetail.as_view(), name='public-quiz-detail'),
    path('public/quizzes/<slug:public_id>/start/', PublicQuizStart.as_view(), name='public-quiz-start'),
    path('public/attempts/<int:attempt_id>/', PublicAttemptDetail.as_view(), name='public-attempt-detail'),
    path('public/attempts/<int:attempt_id>/slots/<int:slot_id>/answer/', PublicAttemptSlotAnswer.as_view(), name='attempt-answer'),
    path('public/attempts/<int:attempt_id>/complete/', PublicAttemptComplete.as_view(), name='attempt-complete'),
    path(
        'public/attempts/<int:attempt_id>/slots/<int:slot_id>/interactions/',
        PublicAttemptSlotInteraction.as_view(),
        name='attempt-slot-interactions',
    ),
    path(
        'quizzes/<int:quiz_id>/project-scores/',
        QuizProjectScoreListCreateView.as_view(),
        name='quiz-project-scores',
    ),
    path('response-config/', ResponseConfigView.as_view(), name='response-config'),
]
