# Generated by Django 4.2.7 on 2025-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizslot',
            name='instruction',
            field=models.TextField(blank=True, default='', help_text='Guidance shown to students when they respond to this slot'),
        ),
    ]
