# Generated by Django 4.2.7 on 2025-11-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizslot_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttemptInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('typing', 'Typing input'), ('rating_selection', 'Rating selection')], max_length=32)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='quizzes.quizattemptslot')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
