# Generated by Django 4.2.7 on 2025-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizattemptinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='identity_instruction',
            field=models.TextField(blank=True, default='Required so your instructor can match your submission.', help_text='Instructions shown to students when confirming their identity.'),
        ),
    ]
