# Generated by Django 4.2.7 on 2025-11-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_identity_instruction'),
        ('quizzes', '0004_quiz_rubric'),
    ]

    operations = [
    ]
