# Generated by Django 4.2.7 on 2025-11-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_merge_0004_quiz_identity_instruction_0004_quiz_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rubric', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='GradingRubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quizzes.gradingrubric')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradingRubricItemLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('points', models.FloatField()),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='quizzes.gradingrubricitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='gradingrubricitemlevel',
            constraint=models.UniqueConstraint(fields=('rubric_item', 'order'), name='unique_rubric_item_level_order'),
        ),
        migrations.AddConstraint(
            model_name='gradingrubricitem',
            constraint=models.UniqueConstraint(fields=('rubric', 'order'), name='unique_rubric_item_order'),
        ),
    ]
