# Generated by Django 4.2.7 on 2025-11-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instructor_profile_picture'),
        ('quizzes', '0006_gradingrubric_gradingrubricitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSlotGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('attempt_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='quizzes.quizattemptslot')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSlotGradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quizzes.quizslotgrade')),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.gradingrubricitem')),
                ('selected_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.gradingrubricitemlevel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quizslotgradeitem',
            constraint=models.UniqueConstraint(fields=('grade', 'rubric_item'), name='unique_grade_rubric_item'),
        ),
    ]
