# Generated by Django 4.2.7 on 2025-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizslotgrade_quizslotgradeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizratingcriterion',
            name='instructor_criterion_code',
            field=models.CharField(blank=True, help_text='Code to match against instructor rubrics', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='quizratingscaleoption',
            name='mapped_value',
            field=models.FloatField(blank=True, help_text="Equivalent value on the instructor's scale", null=True),
        ),
    ]
