# Generated by Django 4.2.7 on 2026-01-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quizratingcriterion_instructor_criterion_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_score', models.FloatField()),
                ('quiz_score', models.FloatField()),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to='quizzes.quiz')),
            ],
        ),
    ]
